-- CREATE TABLE IF NOT EXISTS USERS (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     username TEXT NOT NULL UNIQUE,
--     email TEXT NOT NULL UNIQUE,
--     password TEXT NOT NULL
-- );

CREATE TABLE IF NOT EXISTS USERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    isAccountVerified INTEGER DEFAULT 0,
    verificationToken TEXT,
    verificationTokenExpiresAt DATETIME,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
